### PR TITLE
to_json returns actual json

### PR DESCRIPTION
**Pull request by dapplion**
Current JSON serde implementation returns nested strings inside JSON objects which is not very standard and hard to debug.

### CODE REVIEW

**Comment by asn-d6** [comment]
Slightly confused. What's the relationship between this PR and https://github.com/nalinbhardwaj/curdleproofs.pie/pull/10 ?

Also, there are some merge conflicts since recent merges :(

**Comment by dapplion** [comment]
> Slightly confused. What's the relationship between this PR and https://github.com/nalinbhardwaj/curdleproofs.pie/pull/10 ?

This is PR #10, did you refer to a different PR?

**Comment by asn-d6** [comment]
> > Slightly confused. What's the relationship between this PR and #10 ?
> 
> This is PR #10, did you refer to a different PR?

Ugh sorry. I meant https://github.com/nalinbhardwaj/curdleproofs.pie/pull/6

**Comment by dapplion** [comment]
> > > Slightly confused. What's the relationship between this PR and #10 ?
> > 
> > 
> > This is PR #10, did you refer to a different PR?
> 
> Ugh sorry. I meant #6

- Closed #6 for #14

Having a to / from JSON is still useful for testing and debugging. I would keep the JSON format for a while and use the bytes format for the wire

**Review by asn-d6 — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
